### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by vmbrasseur** [markriedl/easygen#2]
Wow, you've done a ton of work on this project. Thank you!

I was about to share it with my network then noticed that there is no license file. Without that the project is automatically "All Rights Reserved" and no one can legally use it.

Could you please add some sort of (preferably open source) license to the project? I'm happy to help, if you'd like.

**Comment by markriedl** [comment]
There is a MIT license file in the repo. Does this suffice?

**Comment by vmbrasseur** [comment]
You are totally right and I am totally wrong for having missed that. Thanks for the correction!
